name: Notify

on:
  workflow_call:
    inputs:
      tag:
        description: 'Next release tag'
        required: true
        type: string
      channels:
        description: 'Channels to publish development releases'
        required: false
        type: string
  workflow_dispatch:
    inputs:
      tag:
        description: 'Next release tag'
        required: true
        type: string
      channels:
        description: 'Channels to publish development releases'
        required: false
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Test inputs
        env:
          prerelease: ${{ inputs.channels != '' && inputs.channels != null}}
        run: |
          echo "prerelease: $prerelease"
          if [ -z "${{ inputs.channels }}" ]; then
            echo 'input null or empty'
          else
            echo 'input correct'
          fi