name: Notify

name: Release

on:
  workflow_call:
    inputs:
      tag:
        description: 'Next release tag'
        required: true
        type: string
      javawrapperversion:
        description: 'Java Wrapper Version'
        required: true
        type: string
        default: '1.0.57'
      channels:
        description: 'Channels to publish development releases'
        required: false
        type: string
  workflow_dispatch:
    inputs:
      tag:
        description: 'Next release tag'
        required: true
        type: string
      javawrapperversion:
        description: 'Java Wrapper Version'
        required: true
        type: string
        default: '1.0.57'
      channels:
        description: 'Channels to publish development releases'
        required: false
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${{ inputs.tag }}" >> $GITHUB_ENV
      - name: Print env
        run: echo $RELEASE_VERSION
      - name: Test inputs
        env:
          prerelease: ${{ inputs.channels != '' && inputs.channels != null}}
        run: |
          echo "prerelease: $prerelease"
          if [ -z "${{ inputs.channels }}" ]; then
            echo 'input null or empty'
          else
            echo 'input correct'
          fi