name: Notify

on:
push:
    branches: [ branch_name ]
pull_request:
    branches: [ branch_name ]
jobs:

notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send a Notification
        id: notify
        uses: thechetantalwar/teams-notify@v2
        with:
          teams_webhook_url: ${{ secrets.TEAM_HOOK }}
          message: "Github Action Build Number \n logs \n ### TEST "
