name: Notify

on:
  workflow_call:
    inputs:
      tag:
        description: 'Next release tag'
        required: true
        type: string
      channels:
        description: 'Channels to publish development releases'
        required: false
        type: string
  workflow_dispatch:
    inputs:
      tag:
        description: 'Next release tag'
        required: true
        type: string
      channels:
        description: 'Channels to publish development releases'
        required: false
        type: string

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send a Notification
        id: notify
        uses: thechetantalwar/teams-notify@v2
        with:
          teams_webhook_url: ${{ secrets.TEAM_HOOK }}
          message: "Github Action Build Number logs  sdfsd ### TEST "
      - name: Test inputs
        env:
          prerelease: ${{ inputs.channels != '' && inputs.channels != null}}
        run: |
          echo "prerelease: $prerelease"